# -*- coding: utf-8 -*-
"""Copia de Sesion_1_Variables_(1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17E_9s4HnGGCCTSCKkpJMix4c5TCznWeH

# Fundamentos de Programación con Python

<b>¡Bienvenido!</b> 

## Python y Jupyter

Python es un lenguaje de programación usado en ciencias e ingeniería. Es ideal para aprender programación porque su sintáxis es simple y es un lenguaje muy popular en este momento. 

Python permite crear programas que resuelvan problemas automatizando tareas repetitivas, procesando grandes cantidades de datos, resolviendo complejos cálculos matemáticos, o simplemente, creando visualizaciones de fenónenos complejos.

Jupyter es un editor de texto y código que nos permite integrar éstos dos elementos en una página web que llamaremos NoteBook (NB), para poder integrar explicaciones, ejecutar código, e incluir ejercicios prácticos. Cada que encuentres el texto In [ ] a la izquierda de una caja de texto, quiere decir que puedes ejecutar esta instrucción.

## Instrucciones, Variables, y Operaciones Matemáticas
Comencemos por lo más sencillo... Recuerda que programar significa darle instrucciones al computador para que haga lo que yo quiera. Podemos comenzar por pedirle que imprima algo para nosotros:
"""

print("Mi primera instrucción al computador!")

"""### Actividad 1

Lo que hicimos fue simplemente decirle al computador que imprimiera (print) el texto que estaba entre las comillas. Escribe una instrucción para imprimir otro mensaje en el siguiente espacio y luego ejecutalo.

"""

print ('Primera sesión')
mensaje='Hola mundo'
print (mensaje)

"""### Actividad 2
Vamos a modificar el siguiente algoritmo para escribirlo en Python. 

Inicio

    valor_uno ⇐ 5
    valor_dos ⇐ 8

    total =  valor_uno + valor_dos
Fin
"""

valor_uno=5
valor_dos=8

total=valor_uno+valor_dos

"""Por ahora no vemos nada, pero qué tal si imprimirmos la variable total? Ingresa el código para imprimir la variable total"""

print (total)

"""Y si quisieramos leer el valor? Python cuenta con la función input() para leer valores. Vamos a ver como usarla"""

valor_uno = float(input('Ingrese un valor '))
valor_dos = float(input('Ingrese otro valor '))
print(valor_uno + valor_dos)

"""En el código anterior además de la función input() usamos float() para determinar el tipo de dato. Por defecto, Python leería la variable como una cadena de caracteres, pero para poder realizar operaciones aritméticas, necesitamos identificarlas como número. En este caso, float quiere decir flotante. Más adelante analizaremos otros tipos de datos.

Ahora revisemos los operadores aritméticos y su sintáxis en Python

<table>
<thead><tr>
<th>Operador</th>
<th>Nombre</th>
<th>Descripción</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>a + b</code></td>
<td>Suma</td>
<td>Suma de <code>a</code> y <code>b</code></td>
</tr>
<tr>
<td><code>a - b</code></td>
<td>Resta</td>
<td>Diferencia entra <code>a</code> y <code>b</code></td>
</tr>
<tr>
<td><code>a * b</code></td>
<td>Multiplicación</td>
<td>Multiplicación de <code>a</code> y <code>b</code></td>
</tr>
<tr>
<td><code>a / b</code></td>
<td>División real</td>
<td>Resultado de <code>a</code> dividido <code>b</code></td>
</tr>
<tr>
<td><code>a // b</code></td>
<td>División con redondeo</td>
<td>Resultado de <code>a</code> dividido b <code>b</code>, redondeo a número entero</td>
</tr>
<tr>
<td><code>a % b</code></td>
<td>Modulo</td>
<td>Residuo de la división entre <code>a</code> y <code>b</code></td>
</tr>
<tr>
<td><code>a ** b</code></td>
<td>Potencia</td>
<td><code>a</code> a la potencia de <code>b</code></td>
</tr>
<tr>
<td><code>-a</code></td>
<td>Negación</td>
<td>Negativo de <code>a</code></td>
</tr>
</tbody></table>

Observemos la diferencia entre división real y división con redondeo en Python.
"""

print(6/2)
print(5/2)

print(6//2)
print(5//2)

"""### Actividad 3

El área de un cuadrado puede calcularse como a^2. Escribe el código para calcular e imprimir el área del cuadrado donde a = 4

"""

a = 0 # Modificar con el valor dado

# Crea una variable llamada area y usa la formula indicada para calcular el area del cuadrado

a = 4

area= a**2
print(area)