# -*- coding: utf-8 -*-
"""Sesion 3_Condicionales .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DYPztgZlPE-P1D7NRyVoLlNU0t27HIoC

# Fundamentos de Programación con Python

## Condicionales

### Si-Sino-Finsi
Recuerda que los condicionales nos permiten decidir qué instrucciones ejecutar y cuales no. El condicional Si-Sino-Finsi tiene la siguiente estructura:

    Si (condición) Entonces
        instrucción(es)
    Sino
        instrucción(es)
    Fin Si

En Python, esto se escribe un poco diferente y la estructura general depende de las tabulaciónes. Por ejemplo:
"""

x = int(input("Por favor ingresa un número: "))
if x<0:
    print('X es Negativo')
else:
    print('X es Positivo')

print('Esto ya está por fuera del condicional') #Esta fuera porque ya no hay tabulación

"""¿Qué pasa si X es 0? ¿Imprimirá positivo o negativo? ¿Cómo podríamos arreglar este programa para que si X es cero, imprima "X es cero"?


"""

x = int(input("Por favor ingresa un número: "))
if x<0:
    print('X es Negativo')
elif x>0:
    print('X es Positivo')
else:
    print("X es cero")

"""### Operadores lógicos en Python

Antes de pasar a usar condicionales, debemos entender como manejar los operadores lógicos (y/o) en Python para poder evaluar múltiples expresiones al tiempo.

En Python, los operadores lógicos son las palabras en inglés: and y or. Estos operadores nos permiten analizar múltiples expresiones. 

<table>
<thead><tr>
<th>P    </th>
<th>Q    </th>
<th>P And Q</th>
<th>P Or Q</th>
</tr>
</thead>
<tbody>
<tr>
<td>V</td>
<td>V</td>
<td>V</td>
<td>V</td>
</tr>
<tr>
<td>V</td>
<td>F</td>
<td>F</td>
<td>V</td>
</tr>
<tr>
<td>F</td>
<td>V</td>
<td>F</td>
<td>V</td>
</tr>
<tr>
<td>F</td>
<td>F</td>
<td>F</td>
<td>F</td>
</tr>
</tbody></table>

Aquí está el código Python que evalúa las expresiones
"""

print((True and True),(True or True))
print((True and False),(True or False))
print((False and True), (False or True))
print((False and False),(False or False))

"""### Actividad 1

Primero, vamos a pasar los siguientes pseudo-códigos con condicionales a Python

Inicio
    
    a = leer()
    b = leer()
       
    Si a>2 Entonces
        imprimir a
    Fin Si
    
    Si b < 4 Entonces
        imprimir a
    Fin Si
Fin
"""

a = int(input("Ingrese un número "))
b = int(input("Ingrese un número "))
 
if a>2 :
  print(a)
if b < 4:
  print(a)

"""Dado que ambos condicionales imprimen a. Podríamos modificar el código para tener un sólo condicional usando los operadores lógicos?"""

a = int(input("Ingrese un número "))
b = int(input("Ingrese un número "))
 
if a>2 and b < 4:
    print(f"Imprime el valor de {a} ")

"""### Actividad 2

Los operadores lógicos pueden evaluar números y otros tipos de datos.

Para ingresar al programa de medicina, el estudiante debe tener diploma de bachiller y ser mayor de 17 años. Creemos el código para validar esta información dadas las variables tieneDiploma (Y/N) y edad (entero).
"""

tieneDiploma=(input("¿Usted tiene diploma? Responda Y o N "))
edad= int(input("¿Cuántos años tiene? "))

#if tieneDiploma == "Y" or "y" and edad>17: #Esta es una forma para que la Y no importa si es y o Y, será válida
if tieneDiploma.upper() == "Y" and edad>17: #Esta es otra forma
    print("Usted fue aceptado en el programa de medicina")
else: 
    print("Usted no cumple con los requisitos")

"""### Actividad 3

Escribe el código para leer un número entero e imprime SI si el último dígito es 4.
"""

N1=int(input("Escribe un número entero: "))

if N1%10 == 4:    #El %10 sirve para tomar el último número
  print("El número termina en 4")
else:
  print("Pon otro número")

"""Ejercicio #1

Diseña un programa que lea 3 datos de entrada, A, B y C.
Estos corresponden a las dimensiones de los lados de un
triangulo.

El programa debe determinar qué tipo de triángulo es, teniendo en cuenta:

Si solo dos lados del triángulo son iguales entonces es isóceles.

Si los 3 lados son iguales ntonces es equilatero.

Si no se cumple ninguna de las condiciones anteriores, es escaleno
"""

A=float(input("Escriba el lado A: "))
B=float(input("Escriba el lado B: "))
C=float(input("Escriba el lado C: "))

if (A == B == C) :
    print("Es un triángulo equilatero")

elif (A == B) or (A == C) or (C == B):
    print("Es un triángulo isóceles")
else:
    print("Es escaleno")

"""Ejercicio #2

Construya un algorítmo que pida tres números y los muestre ordenados
(de mayor a menor
"""

N1=int(input("Ingrese un número "))
N2=int(input("Ingrese un número "))
N3=int(input("Ingrese un número "))

if N1>N2 and N1>N3:
   if N1>N3 and N1>N2:
     print("De mayor a menor es ", N1, ",", N2, ",", N3)
   else:
     print("De mayor a menor es ", N1, ",", N3, ",", N2)
elif N2>N1 and N2>N3:
   if N2>N3 and N2>N1: 
     print("De mayor a menor es ", N2, ",", N1, ",", N3)
   else:
        print("De mayor a menor es ", N2, ",", N3, ",", N1)
elif N3>N2 and N3>N1:
    if N3>N1 and N3>N2:
      print("De mayor a menor es ", N3, ",", N2, ",", N1)
    else:
      print("De mayor a menor es ", N3, ",", N1, ",", N2)
else:
    print("Ingresó número iguales", N1, ",", N2, ",", N3)

"""Ejercicio #3

Realiza un programa que simule el lanzamiento de dos dados aleatoriamente e indique si ambos dados son iguales "¡Eureka!" o un mensaje que diga "Sigue intentando".
"""

import random 

dado1=random.randint(1,6)
dado2=random.randint(1,6)

if dado1 == dado2:
  print(dado1, "-", dado2,"¡Eureka, son pares!")
else:
  print(dado1, "-", dado2,"Que mala suerte, sigue intentando")

"""# Ejercicio #4

Un empleado necesita calcular su salario semanal, el cual se obtiene de la siguiente manera.

Si trabaja 40 horas se le paga 35000 por cada una de las primeras 40 horas y 55000 por cada hora extra
"""

horas=float(input("Digite la cantidad de horas que trabajó "))

if horas<=40 :
  salario = round(horas*35000)
  print(f"El total de horas normales trabajado fue de {salario} aproximadamente")
else:
  salario= round(40*35000 + (horas-40)*55000)
  print(f"El valor de las horas extras trabajadas fue de {salario} aproximadamente")

"""Ejercicio #5

La política de cobro de una compañía telefónica es: cuando se realiza una llamada, el cobro es por el tiempo que esta dura, de tal forma que los primeros cinco minutos cuestan 100 pesos por minuto, los siguientes tres, 80 pesos, los siguientes dos minutos, 70 pesos y a parti del décimo minuto, 50 pesos.

Además, se carga un impuesto de 3% cuando es domingo, y si es otro día en turno de mañana 15% y en turno de la tarde 10%.

Realice un algoritmo para determinar cuánto debe pagar por cada concepto una persona que realiza una llamada.
"""

tiempo=int(input("Digite los minutos que habló "))
domingo=input("¿Era domingo? S/N ")

if tiempo <= 5:
	costo= tiempo*100
elif (tiempo > 5) and (tiempo <=8):
	costo= 5*100 + (tiempo - 5)*80
elif (tiempo > 8) and (tiempo <= 10):
	costo= 5*100 + 3*80 + 2*70 
else:
	costo= 5*100 + 3*80 + 2*70 + (tiempo - 10)*50
if domingo.upper() == 'S':
	costo= costo*1.03
else:
	jornada = input("Indique si era Mañana (M) o Tarde (T): ")
	if jornada.upper() == "M":
		costo= costo * 1.15
	else:
		costo= costo* 1.10
print(f"El costo de la llamada es: ${costo}")